name: molopt
channels:
  - rdkit
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - absl-py=0.10.0
  - alabaster=0.7.12
  - asn1crypto=1.3.0
  - astroid=2.3.3
  - attrs=19.3.0
  - autopep8=1.4.4
  - babel=2.8.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - blinker=1.4
  - boost=1.68.0
  - boost-cpp=1.68.0
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.7.22
  - cachetools=4.1.1
  - cairo=1.14.12
  - catalogue=1.0.0
  - certifi=2020.6.20
  - cffi=1.13.2
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.2.2
  - cryptography=2.8
  - cuda90=1.0
  - cuda91=1.0
  - cuda92=1.0
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - cymem=2.0.2
  - cython-blis=0.4.1
  - dbus=1.13.12
  - decorator=4.4.1
  - deepsmiles=1.0.1
  - defusedxml=0.6.0
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.6
  - firefox=70.0.1
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.63.1
  - gmp=6.1.2
  - google-auth=1.21.2
  - google-auth-oauthlib=0.4.1
  - grpcio=1.31.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.8
  - imagesize=1.2.0
  - importlib-metadata=1.7.0
  - importlib_metadata=1.5.0
  - inflect=4.1.0
  - intel-openmp=2019.4
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - jaraco.itertools=5.0.0
  - jedi=0.16.0
  - jeepney=0.4.2
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=5.3.4
  - jupyter_console=6.1.0
  - jupyter_core=4.6.1
  - keyring=21.1.0
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.3
  - libboost=1.67.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.11.2
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markdown=3.2.2
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - memory_profiler=0.55.0
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - molvs=0.1.1
  - more-itertools=8.2.0
  - murmurhash=1.0.2
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - ninja=1.9.0
  - nltk=3.4.5
  - nose=1.3.7
  - notebook=5.7.4
  - numpy=1.17.3
  - numpy-base=1.17.3
  - numpydoc=0.9.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openssl=1.1.1h
  - packaging=20.1
  - pandas=1.0.0
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.6.0
  - patsy=0.5.1
  - pcre=8.43
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.1.1
  - pixman=0.38.0
  - preshed=3.0.2
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - protobuf=3.11.2
  - psutil=5.6.7
  - ptyprocess=0.6.0
  - py-boost=1.67.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycairo=1.18.0
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pyflakes=2.1.1
  - pygments=2.5.2
  - pyjwt=1.7.1
  - pylint=2.4.4
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - python=3.7.4
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.4.0
  - pytz=2019.3
  - pyzmq=18.1.1
  - qt=5.9.7
  - qtawesome=0.6.1
  - qtconsole=4.6.0
  - qtpy=1.9.0
  - rdkit=2020.03.2.0
  - readline=7.0
  - requests=2.22.0
  - requests-oauthlib=1.3.0
  - rope=0.16.0
  - rsa=4.6
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - secretstorage=3.1.2
  - send2trash=1.5.0
  - setuptools=45.1.0
  - sip=4.19.8
  - six=1.14.0
  - snowballstemmer=2.0.0
  - sphinx=2.3.1
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.3
  - spyder=3.3.6
  - spyder-kernels=0.5.2
  - sqlite=3.31.1
  - srsly=1.0.0
  - statsmodels=0.11.0
  - tensorboard=2.2.1
  - tensorboard-plugin-wit=1.6.0
  - tensorboardx=2.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - torchtext=0.5.0
  - tornado=6.0.4
  - tqdm=4.36.1
  - traitlets=4.3.3
  - ujson=3.2.0
  - urllib3=1.25.8
  - wasabi=0.6.0
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - wurlitzer=2.0.0
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=2.1.0
  - zlib=1.2.11
  - zstd=1.3.7

